CREATE DATABASE "Admin";

CREATE TABLE IF NOT EXISTS public."Scheduler"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date_post TIMESTAMP,
	text_post text,
    image_id text,
    sticker_id text,
    CONSTRAINT "Scheduler_pkey" PRIMARY KEY (id)
)


CREATE TABLE IF NOT EXISTS public."TestAdmin"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ) PRIMARY KEY,
    date_post TIMESTAMP,
	text_post text,
    image_id text,
    sticker_id text,
    CONSTRAINT "TestAdmin" PRIMARY KEY (id)
)

